### ISSUE TITLE
BatList.n_cartesian_product

### ISSUE THREAD

**Issue by wistery-k** [ocaml-batteries-team/batteries-included#359]
Is there any reason for
BatList.n_cartesian_product [] = assert false
?
I think [[]] is good (or at least invalid_arg) instead of assert false.

**Comment by murmour** [comment]
True story:

In 2012, young Max Mouratov wrote a bunch of code that used `n_cartesian_product` for "give me all combinations of items from the given lists, so I can do something useful to each of them".

In 2013, young Gabriel Scherer found the One Right Answer to "what should `n_cartesian_product []` be", and wrote a deep blog post about it: http://gallium.inria.fr/blog/on-the-nary-cartesian-product/.

In 2023, the bunch of code that young Max wrote in 2013 suddenly broke on a particular input, and the now old Max discovered that `n_cartesian_product []` returns `[[]]`, and not `[]` as the young Max expected (by intuition). But `[]` was not "something useful" in all the code that young Max wrote, and the old Max sympathized with the young one.

Then, the old Max read the deep blog post by the young Gabriel, and his IQ increased by one point. He understood the secrets of the universe, and the whole truth unfolded before him.

The blog post ends with a bit of infinite wisdom:
> No theoretical considerations make as strong an argument as this one: the right answer is the one that makes the code elegant.

So, the old Max pondered about it for a while, and his mind got illuminated by the brightest idea ever. He copied the implementation of `n_cartesian_product` from Batteries and replaced `[[]]` with `[]` inside it, because it was an elegant and practical solution that saved him from sprinkling `if l = []` all over his client code, in all of his programs.

There is no morale.

But the old Max from 2023 suggests that perhaps it'd be wise to document this corner case in the docstring of `n_cartesian_product`, because its behaviour is not quite intuitive, and not quite obvious to those programmers who aren't type theorists. He also wonders if the old and wise Gabriel from 2023 has any new thoughts on the matter now.

**Comment by UnixJunkie** [comment]
If you send an improvement for the ocamldoc of this function, I will gladly merge it.
