### ISSUE TITLE
split for BatArray

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#443]
I'd like a split for arrays.
It would do roughly what split does for sets.
PRECONDITION: the array is sorted in increasing order

**Comment by gasche** [comment]
`split` was just merged in master, will be part of 3.0.

**Comment by rixed** [comment]
Reopening as we have too many Array.splits now: this one, that's been waiting on the v3 branch for a while and for a reason that eludes me, and another one added on master more recently that mimick List.split in that it splits an array of pairs into a pair of arrays.

To solve this conflict of name, I suggest @UnixJunkie  and @c-cube go fight a pistol-duel next Sunday morning and we keep the survivor's implementation, or I merely rename this split into something like "pivot_split", because that's what it evokes to me, unless someone has a better suggestion?

**Comment by UnixJunkie** [comment]
Your renaming is fine.

**Comment by UnixJunkie** [comment]
Fixed in v3.
