### ISSUE TITLE
combination/permutations combinators

### ISSUE THREAD

**Issue by c-cube** [ocaml-batteries-team/batteries-included#503]
Someone on IRC asked whether some OCaml library provided functions to generate permutations or combinations of a bunch of elements. I didn't see any in Batteries (although I may have missed them in some module); they seem very useful for many algorithms and are not trivial to implement, so I think it may be a good idea to add at least `BatList.combinations` and `BatList.permutations`. An in-place generator for arrays is also doable (see C++'s STL).

**Comment by gasche** [comment]
Where are we on this? @c-cube recalled us that this PR is undecided (thanks!), but it's not clear to me what the best move is. The code as proposed by @Chimrod is not mergeable as-is (because of the french wordings), and there is a debate on the interface.

I wouldn't mind adding a `BatCombinatorics` module with a more polished version of @Chimrod code, but given the absence of dependencies on anything else in Batteries I also think that it would be served just as well as an independent package available on opam, that non-Batteries users may have less qualms including. (There already is [backtracing/combine](https://github.com/backtracking/combine), but it seems more about constraint resolution than arithmetic enumerations.)

**Comment by c-cube** [comment]
Side note: there is also

```ocaml
val Gen.permutations : 'a gen -> 'a list gen                                                 
val Gen.permutations_heap : 'a gen -> 'a array gen 
val Gen.combinations : int -> 'a gen -> 'a list gen
```

**Comment by UnixJunkie** [comment]
Now we have those in BatLazyList, thanks to @c-cube
