### ISSUE TITLE
List.sum fails on empty list

### ISSUE THREAD

**Issue by c-cube** [ocaml-batteries-team/batteries-included#519]
Strangely, `List.sum` fails on the empty list (instead of returning 0), but `Enum.sum` returns 0 in this case (same for `fsum`).

I guess this will have to wait until 3.0, but still, it's strange.

**Comment by UnixJunkie** [comment]
Shouldn't this go in our upcoming release?

**Comment by gasche** [comment]
I think we should keep it for the next major version push (3.0), because it breaks backward-compatibility. It is not a bugfix or a new feature, but something that improves consistency at the cost of changing a *specified* behavior.

You *could* decide to make the coming release a major release, but I suspect that it's a bit ambitious after our failure to get releases out in the past few month. I would be in favor of getting a release that is as polished and small-scope as possible now, to put a better release cycle on its rails, and later decide when we want our next major release and what to have in it -- for example some of @c-cube more ambitious inter-module dependency cuts.

**Comment by UnixJunkie** [comment]
I just hit this bug, again...

**Comment by rixed** [comment]
@UnixJunkie : there is no such function as `prod` or `fprod` it seems.

**Comment by UnixJunkie** [comment]
@rixed yes, they might be useful. Be careful that such functions could also be reflected in BatArray.
sum/fsum also are in BatArray. For consistency, we might want to return 1 (or 1.0) in the empty data structure case and document it.
