### ISSUE TITLE
BatSet.update

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#613]
I wonder if it would be possible to implement an update operation that would be more efficient than

    add new_x (remove old_x set)

**Comment by gasche** [comment]
Not really, because in general we have no information on where the updated element should be placed in the ordered set (it may end up arbitrarily far away from the initial element). At best you might be able to reason on the imbalance precisely enough to do less rebalancing during the `remove` (it's ok if the intermediate set is not fully-balanced) and reconstruct balance during the `add`, but that seems relatively complex for little gain -- but I'm sure some people have worked on that before, and maybe the actual solution is simple enough to implement, so pointers would be welcome.

What we could do is optimize for the case where the updated element has the same ordering as the pre-update element (for example your elements are record and you update a field that is not taken into account by the comparison operation). We might either compare the old and the new value, and use an update-in-place if they are equal, or even compare the new value to the biggest element before and the smallest element after the previous value to decide the update-in-place (more costly to check, but apply is slightly more scenarios where the value has changed but "only a little" in a sparse-enough set). Both cases would still need to have specific code for `update` (a zipper-returning solution would be more modular but less efficient), so that means increase in codebase.

PS: I believe that besides the abstract modules Set and Map (functorized or not), it would be nice to expose a *non-abstract* implementation that would allow users to implement this kind of things without having to ask us to modify the internals. That is more or less what `BatAvlTree` was supposed to become, but that has not happened yet.

**Comment by UnixJunkie** [comment]
My use case would be the one you mentioned: new_x and old_x compare equal with the comparator
function you use to build your set, but are not physically equal.

Wouldn't an update-in-place break the purely functional nature of sets?
I do not want that.
I just want to avoid the re-balancing that may happen when you do
my update operation in the naive way I mentioned (add new_x (remove old_x set)).

**Comment by gasche** [comment]
When I said "update in place", I meant "put at the same place in the ordered set, without rebalancing". That is, "put in the same place (in a new tree)" rather than a mutation operation. That was indeed a very bad reuse of existing naming, sorry.

**Comment by UnixJunkie** [comment]
Any idea why this doesn't compile ?
https://github.com/UnixJunkie/batteries-included/tree/batSet_update
I am puzzled.

**Comment by gasche** [comment]
I have not tried to compile this, but below is a comment on [your patch](https://github.com/UnixJunkie/batteries-included/commit/441103a69336bcaf277b65992d06969237791036).

The documentation in the `.mli` is not satisfying. First, it is inconsistent across the several `update` functions. You should either have the exact same documentation, or have some of the copies redirect to a full-documented one.

Second, and this is more problematic, it is not explicit about the fact that the new value must have the same ordering as the old value -- having a `@raise` clause for this is not enough, the description text must be explicit about this. Suggestion:

    [update x y s] returns a set containing all elements of [s],
    except that [x] was replaced by an element [y] which must
    have the exact same key ordering.

I am worried that users would try to use `update` without reading this documentation first: from the name and the type it would be natural to use it with not-same-order values. I think that is a blocker for merging the interface as proposed. I see two solutions:

1. Rename this function to make the same-order limitation explicit, for example something as `update_same` or `update_equal`.
2. Make this function *work* when passed non-same-order values: if you detect that the values are not same-ordered, just call `remove` and `add`. We would still document the efficiency advantage of the fast path.

My personal impression is that option (2) would provide the most value to our users, but I would also be fine with option (1), and maybe you have other ideas.

**Comment by UnixJunkie** [comment]
My use_case is really update_equal.
But your 2) suggestion is easy to implement, I will do this.
If any maintainer has an idea of why the code is not compiling, I'll gladly take it.
I am really blocked by that.

**Comment by UnixJunkie** [comment]
update was accepted
