### ISSUE TITLE
Set.pop

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#614]
pop s = ((min_elt s), remove (min_elt s) s)
but implemented in a more efficient way, could be useful

**Comment by thelema** [comment]
Why `min_elt s`? Why not `choose s`? Maybe 3 pops: pop_min, pop_max and
pop_choose?
E.

**Comment by UnixJunkie** [comment]
Yes (@c-cube also told me almost the same thing yesterday evening).

**Comment by UnixJunkie** [comment]
pop_min is here:
https://github.com/ocaml-batteries-team/batteries-included/pull/618

**Comment by UnixJunkie** [comment]
I can contribute pop_max soon.
However, I don't see how pop_choose could be implemented in an efficient manner.

**Comment by UnixJunkie** [comment]
There is pop_max here:
https://github.com/ocaml-batteries-team/batteries-included/pull/619
on top of pop_min

**Comment by gasche** [comment]
I think it would make sense to also implement them for `Map` (retrieving the max key and its binding). The same comment applies to `at`: it's better to keep those two modules synchronized as much as we can, because the effort to write features for both is low, whereas the effort to re-synchronize them after the fact is much higher.

**Comment by UnixJunkie** [comment]
I can do it.
I will create different issues to track them.

**Comment by gasche** [comment]
I just re-noticed that `Set` [already has pop](https://github.com/ocaml-batteries-team/batteries-included/commit/45ab5a159bd023f91f6e1428b7456cb412381381) -- but the proposed `pop_min` and `pop_max` are still useful.

**Comment by gasche** [comment]
I have a "contribution process" question: given that I'm relatively limited in time these days, I think that it would be easier for me to integrate all the coherent changes at the same time, rather than one at a time. I'm fine with splitting the changes in separate issues and reviewing separate pull requests, but I would rather wait to see the complete picture and merge everything.

My question is: is that process ok with you? If it is important for your own motivation to contribute that the current PRs be merged as soon as they are mergeable,  then we can go for this.

By "coherent change" I mean the set of change that moves us from the interface as it exists now, to an interface that feels complete and consistent. It would make no sense for users to observe a state where `pop_min` is available but `pop_max` is not, for example, and I would argue that we similarly should have `Map.pop_min` and `Map.pop_max` available as well.

Asking for coherent states before merge has the disadvantage of requiring contributors to do more upfront work; but I think that this work needs to be done in any case, and it is not in my current capacity to do it on the contributor's behalf, so I'm not sure how to avoid that.

**Comment by UnixJunkie** [comment]
Hello. Yes, I would like to see my changes merged as soon as possible.
In my point of view, it is already hard enough to get my changes accepted into batteries.
Please don't make this any harder, really.

**Comment by UnixJunkie** [comment]
pop_min and pop_max were accepted
