### ISSUE TITLE
make test should compile a native exe

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#617]
the time to pass all tests being far greater thant the time to compile

**Comment by UnixJunkie** [comment]
On my machine, with all tests passing:

    time make 10.756s
    time _build/testsuite/main.byte 57.429s
    time _build/testsuite/main.native 10.890s

**Comment by gasche** [comment]
Note that native compilation could be made considerably quicker on re-compilation after a small change by making use of the `-opaque` option added to OCaml 4.02: with this option, cross-module optimisations are disabled, which generates slightly slower code but does not require recomputing the modules that depend on a modified module (if the interface has not changed).

(My current edit-and-test feedback loop is to use byte compilation but change the `TESTABLE` variable to only include the module being affected, so that both compilation and testing are fast. `TESTABLE` only works for inline tests, though, the testsuite is still monolithic.)

**Comment by UnixJunkie** [comment]
I'm stupid, I just looked at the makefile and found
the target make test-native:

    make clean && time make test-native 
    real    0m35.707s

    make clean && make test
    real    1m24.804s

I'll use that or use your TESTABLE variable trick from now on.
