### ISSUE TITLE
About ppx

### ISSUE THREAD

**Issue by xvw** [ocaml-batteries-team/batteries-included#638]
It seems to me that before, Batteries used syntaxes extensions.
What is your opinion as to update them using PPX? 
(Perhaps is it irrelevant?)

**Comment by gasche** [comment]
Batteries syntax extension were removed because they proved difficult to integrate in most people's workflow. We *could* use ppx extensions, which I think solve that problem (at least partially: the build system integration can still be an issue for some users), but we would need good justification of the  value they add to Batteries.

**Comment by xvw** [comment]
Ok ! I have ask that because I would contribute, but if we don't need extension... :) 
Thanks for your quick answer !
