### ISSUE TITLE
get rid of the .mlv/.mliv files

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#658]

**Comment by gasche** [comment]
For the record I made an experiment this week-end with a [cppo branch](https://github.com/gasche/batteries-included/tree/cppo) in my private repository. I converted two modules to use cppo instead of the local build/prefilter, [Array](https://github.com/gasche/batteries-included/commit/7ab5a65d56d275a558ecb47cd1a07e9da0a0caae) and [Bigarray](https://github.com/gasche/batteries-included/commit/588c54f8da7c2aa0f6429c3e0bd07eebbba11a12).

The results are mixed. The good things about cppo:
- it is standard; people know about it, they may have adapted their editor-mode configuration to recognize `.ml.cppo` extensions, etc.
- it has other features than filtering on the version that we might use in the future (but we don't need them for now): defines, inclusion, etc.
- it supports a richer language of version condition; in particular, "and" and "or" are definable, so you could enable some code on some like `(v > 4.0 && v < 4.2) ||| (v = 4.3.1)`, which we cannot do without duplication (or more development) with build/prefilter -- but we don't need it for now.

The bad thing is:
- it makes an additional dependency (but I'm fine with that)
- the syntactic overhead is actually larger (see the examples above), so the code could become *harder* to read
- it cannot prefilter line inside comments, which mean that comments with some part that are conditional on some versions would need to be duplicated.

All in all, I think "cppo is more standard" is the killer argument and it's *worth* converting, but it's also a lot of (boring) work and, as you can see, the benefits are not so clear-cut. I'm putting this on hold and concentrating on getting 4.03-ready releases.

If someone is interested in working on helping on that, please feel free to say something here.

**Comment by UnixJunkie** [comment]
Are you forced to have X.ml.cppo ?
Can't you have X.ml and then tell the build system that this file needs preprocessing?

**Comment by gasche** [comment]
Using a specific extension seems standard among `cppo` users (see [utop](https://github.com/diml/utop/tree/master/src/lib)) for example, but now that I think of it Jérémie seems to use `.cppo.ml`, which is better editor-wise and such, so I should probably use that. I'm fine with whatever the ocamlbuild plugin provided with `cppo` allows, but I personally like the idea of having an explicit mark somewhere that the code is not *quite* standard OCaml, but has some extra stuff. (We could use `.v.ml` for our stuff as well, I guess?)

**Comment by UnixJunkie** [comment]
cppo is no more maintained I think; there is this one which is kind of new: https://github.com/thierry-martinez/metapp

**Comment by gasche** [comment]
`ppx_optcomp` would be the ppx equivalent of cppo, and seems actively maintained. (I don't know about cppo maintenance status.) metapp seems interesting but more powerful and less used.

**Comment by UnixJunkie** [comment]
The syntax of ppx_optcomp looks simpler than metapp.
However, installing ppx_optcomp requires: ocaml-migrate-parsetree, ocaml-compiler-libs and ppxlib.
Exact dependencies for metapp.
I am worried that such dependencies could not be available on some ocaml versions, which would make batteries
impossible to compile for those old versions.
On the other hand, cppo just requires dune>=1.0 and base-unix (which should not count because it comes with an ocaml install).

**Comment by UnixJunkie** [comment]
I might take a shot at this issue during the winter holidays.
If maintainers agree on the preprocessor we should use for the next 10 years, that would help.
@c-cube do you use a preprocessor in containers?

**Comment by c-cube** [comment]
No, in containers I only use `dune` and [small OCaml scripts](https://github.com/c-cube/ocaml-containers/blob/master/src/core/mkshims.ml) to generate code depending on the OCaml version. All the code is valid OCaml because I can't live without merlin.

**Comment by UnixJunkie** [comment]
There is another path: write a single file, pure OCaml dumb-simple preprocessor that would live in batteries' code base,
supporting only the feature set used by batteries.
I like this wild path.

**Comment by gasche** [comment]
> There is another path: write a single file, pure OCaml dumb-simple preprocessor that would live in batteries' code base,
supporting only the feature set used by batteries.

I'm confused, is this not exactly what we have today?

**Comment by UnixJunkie** [comment]
We rely on campl4 currently (according to the myocamlbuild.ml file; though I honestly know almost nothing about ocamlbuild).

**Comment by gasche** [comment]
We don't use camlp4 (otherwise it would be marked as a dependency in the opam file); the myocamlbuild.ml camlp4 stuff makes it convenient to hook camlp4 in the build system by adding stuff in `_tags`, but it is not currently used. The preprocessor we use is [build/prefilter.ml](https://github.com/ocaml-batteries-team/batteries-included/blob/ab4ada0/build/prefilter.ml) and its (pretty simple) build-system plumbing is [here in myocamlbuild.ml](https://github.com/ocaml-batteries-team/batteries-included/blob/ab4ada0/myocamlbuild.ml#L56-L70).

**Comment by hhugo** [comment]
In jsoo, I implement an equivalent of ppx_optcomp with just what I need to keep dependencies under control. https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/ppx/ppx_optcomp_light.ml

**Comment by gasche** [comment]
This approach would have the benefit of making our sources-with-preprocessing-directives valid OCaml files, using attributes or extensions, so in particular Merlin would be able to work with the source files. But then it requires a dependency on Ppxlib and it requires using Dune. I think that using Dune would be a good choice, and I have no clear opinion on the Ppxlib dependency. But a simpler approach would be to keep our own home-grown preprocessor, but change the processing marks that we recognize to be OCaml comments, so that Merlin works correctly most of the time.

**Comment by UnixJunkie** [comment]
yet another solution would be to make merlin aware of preprocessors

**Comment by UnixJunkie** [comment]
If we get rid of ocamlbuild (thanks to dune), I guess we will be able to get rid of all the .ml{i}v files
and just use .ml{i} files.
I would like this, because then there is no ambiguity about which file we are supposed to edit.
Also, syntax highlighting will always work, etc.
