### ISSUE TITLE
Date seems to be missing

### ISSUE THREAD

**Issue by angrygoats** [ocaml-batteries-team/batteries-included#683]
After playing around with batteries-included I can't seem to find `Date`. 

Following the example [here](https://github.com/ocaml-batteries-team/batteries-included/blob/4f41b77c16d2311238de3a4afc0ab240d9692c5a/examples/tools/now.ml#L8) I try to `open Date` and I get `unbound module Date`. 

I am unsure how to use this feature of batteries included. [This](http://batteries.forge.ocamlcore.org/doc.preview:batteries-beta1/html/api/Date.html) link seems to be the API documentation.

Can anyone help me with this? Thank you!

**Comment by gasche** [comment]
Hi,

Unfortunately, this is an link to the documentation of a fairly old version
of Batteries; if you click "up", you'll see a page that says

Welcome to OCaml Batteries Included Beta 1.
>

Batteries has evolved a lot since then, and one of the changes was to slim
it down. You may find a more up-to-date documentation by following the "API
Docs" link from the homepage
  http://batteries.forge.ocamlcore.org/
  http://ocaml-batteries-team.github.io/batteries-included/hdoc2/

For manipulate dates, I had good experiences with the Calendar package
available through opam:
  http://opam.ocaml.org/packages/calendar/calendar.2.03.2/

**Comment by c-cube** [comment]
I think we really should remove the documentation of v1…

**Comment by UnixJunkie** [comment]
+1 for the removal of the old doc that gets everybody confused in google.
@angrygoats For your Date problem: there are the calendar, odate and ptime libraries in opam.

**Comment by angrygoats** [comment]
@gasche Thank you - I just really liked the API of the Date you guys once had. I will check out the alternatives everyone mentioned.

**Comment by gasche** [comment]
If you were interested in making this module your own and maintain it, you
could package it as an independent library on OPAM. The code for old
Batteries versions can be found at
  https://forge.ocamlcore.org/frs/?group_id=17

In general I think that well-designed independent building blocks are more
useful to the community at large than big monolithic libraries. We could
not do it at the birth of Batteries because we had no consensus on package
management, but it is possible now, and we should not hesitate.

**Comment by hcarty** [comment]
@angrygoats It looks like the old `Date` module was really an inclusion of/wrapper around ocamlnet's `Netdate`: http://projects.camlcity.org/projects/dl/ocamlnet-4.1.2/doc/html-main/Netdate.html

`ocamlnet` should be installable from opam if you're interested in using it as-is.

**Comment by fccm** [comment]
Then this file is out of date and should be removed:
[examples/tools/now.ml](https://github.com/ocaml-batteries-team/batteries-included/blob/master/examples/tools/now.ml)

**Comment by UnixJunkie** [comment]
@fccm I removed the file. Thanks for the heads up.
