### ISSUE TITLE
Documentation: IntMap

### ISSUE THREAD

**Issue by 01mf02** [ocaml-batteries-team/batteries-included#692]
In the documentation for batSet:
 
> You can also use predefined maps such as IntMap for maps with integer keys.

However, IntMap is nowhere defined. Still, a predefined IntMap would be very convenient to have!

**Comment by gasche** [comment]
Correct, `IntMap` was removed in f26ecc8b9dcdef87e11236186194702c904167b9 in 2012.

On the other hand, it's fairly easy for users to redefine as `BatMap.Make(BatInt)` (or `Map.Make(Int)` if you `open Batteries`), and because it's an applicative functor two definitions in this form will return the same module (the types will be compatible). My personal inclination would be to replace this mention by an example of defining `IntMap` and `StringMap` that way. (One reason why is that it avoids having a dependency from the `Map` module to `Int` and `String`, which would be an issue if we decided one day to use balanced map in a `String` algorithm for example.)

Would you say that having `IntMap` predefined would really be better than `module IntMap = BatMap.Make(BatInt)`

**Comment by 01mf02** [comment]
I did not know about `Map.Make(Int)`, which is really handy.
I added your examples to #693 and think that this makes a definition of IntMap obsolete.

**Comment by thizanne** [comment]
See #727
