### ISSUE TITLE
Safe, high-level subprocess management

### ISSUE THREAD

**Issue by vog** [ocaml-batteries-team/batteries-included#858]
Batteries, like every other library, should encourage safe interfaces by making them more convenient than unsafe interfaces.

In particular, the safe process execution via "proc:string + args:string list" should be encouraged over shell command execution.

However, the nice, high-level `open_process` function is only available for shell commands. For safe execution (proc+args) there is only `create_process` which is relatively low-level.

Is there anything like `open_process` for proc+args?

Moreover, is there any interest in Batteries to provide a unified high-level interface for calling and communicating with subprocesses, similar to Python's `subprocess` module? (maybe with a nicer API than subprocess, but you get the idea.)

**Comment by vog** [comment]
Pardon my ignorance, but won't it take quite a long time to get this into the OCaml standard lib? Isn't the whole point of Batteries to speed up that process?

Moreover, what about cleaning up the mess? Shouldn't we strive for a simple, more consistent high-level API for subprocesses? For example, the function names should be short and clear. There should be just one set of functions (in/in_out/in_out_err) where env/no-env as well as shell/proc+args is just a matter of different parameters, and so on.

Would that be a sub module of Unix? Would that go into a separate Batteries module? Or, would that have to be separate OPAM package as that would be too high-level for Batteries?

**Comment by gasche** [comment]
I think that the specific need you pointed to can be solved by just adding one function that integrates relatively nicely within the current API. Given that the API is reused from the stdlib, the most rewarding move (in term of number of users whose life improves) is to contributed at the stdlib level. It is indeed easier to get something integrated into Batteries, but getting stuff upstream is not impossible and you would get higher-quality feedback there, as there are more experts of these matters than among just the Batteries contributor.

Now if you want to revamp the subprocess API to propose a radical new, more coherent design, I think that is also an interesting idea to consider in parallel (the two contributions are complementary, I think), and indeed the stdlib may not be the best host for that. Why not Batteries, but another option you should consider is having an independent library for just this; this is a well-defined need that does not rely on particular Batteries feature (the BatUnix module does rely on the higher-level `input`/`output` abstractions of Batteries, but it turns out people don't like that very much and that a lower-level API would have better chances of adoption); you would have a larger adoption base if you presented to the world a small library that does subprocess well, rather than if they have to add Batteries as a dependency to do this.

I wonder if such a library doesn't already exist -- maybe we could point at it (or them) in the relevant place of the Batteries documentation -- for example maybe [Spawn](https://opam.ocaml.org/packages/spawn/) is such a suitable, smaller library.

I think the OCaml community is moving away from monolithic libraries to smaller, independent libraries when possible. When it makes sense to improve the monoliths, it is very nice to do it, but when the monolithic aspect does not add value to the proposed change I would recommend working outside of them.

**Comment by vog** [comment]
Thanks for the clarification! So Batteries is indeed not the right place to start with that.

Also, thanks for the pointer to the Spawn library! This is indeed almost what I had in mind. I just proposed some ideas and asked some questions on their issue tracker.

Finally, I proposed `open_process_args` to the OCaml standard library: https://caml.inria.fr/mantis/view.php?id=7794

**Comment by UnixJunkie** [comment]
Do you have some code already?
Sorry I'm late, but I think it does have its place in the Unix module.
Because, waiting for things to enter the stdlib can take quite some time and end-up nowhere.

**Comment by gasche** [comment]
`Unix.open_process_args`{,`_in`,`_out`,`_full`} have been added to the standard Unix library and will be available starting from OCaml 4.08 -- not the upcoming 4.07 release, but the one after that, to be released around winter 2018.
