### ISSUE TITLE
Problem with parsing negative float strings in batNum.of_float_string

### ISSUE THREAD

**Issue by mthark** [ocaml-batteries-team/batteries-included#886]
We are using batNum.of_float_string to parse Strings of floating point representations. However, negative floating points with leading zeros are parsed incorrectly. For example, "-0.5"|>batNum.of_float_string |> batNum.to_string yields "1/2" instead of "-1/2". I guess that when the String is splitted at the dot, the first part, which is "-0", is converted to "0" and the leading "-" is lost.

**Comment by gasche** [comment]
Indeed, this is what is happening. Thanks for the report!

**Comment by gasche** [comment]
I believe that this should now be fixed by #887.

Note: `of_float_string` was already not an efficient operation, and my fix simplifies the code but makes it slightly slower again. You should not use it in speed-constrained code. (You should probably be using Zarith if you want efficient arbitrary-precision numbers.)
