### ISSUE TITLE
next (minor) release

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#903]
I am opening this to track it.

**Comment by UnixJunkie** [comment]
It will be 2.10.0.

**Comment by UnixJunkie** [comment]
I did one pass on the PRs.
Some old ones were merged.
Tests are passing on 4.06.1.

**Comment by UnixJunkie** [comment]
Tests are OK on 3.12.1, after some fixes.

**Comment by UnixJunkie** [comment]
Tests are OK for 4.08 now.

**Comment by UnixJunkie** [comment]
I am stopping for today at the release marking step of howto/release.md.

**Comment by gasche** [comment]
I'm in holidays now and not available to help with this (I don't think I will be able to go through the batteries notifications before I come back to work) -- thanks for doing this work!

I would like to test that we build with OCaml 4.09 sometime soon, and will maybe send some code updates along the way.

(Note: the compat-test is somewhat broken right now, I think, because we haven't backported some of the more recent stdlib improvements into Batteries. I don't think we can realistically hope to import all of them, so maybe we should give up on that test.)

**Comment by UnixJunkie** [comment]
I had to introduce many fixes (mostly via preprocessing), but even compat-test is working.

**Comment by gasche** [comment]
Thanks! That's a lot of work, for compatibility both with newer and older releases.

The fixes you pushed enable new library functions only on newer OCaml releases, not on older releases. Usually what we dd instead was to try to support each function (when possible: they don't rely on a runtime capatibility) on older OCaml releases as well -- so that the Batteries interface is mostly the same for all OCaml versions. This work is now carried over by [stdcompat](https://github.com/thierry-martinez/stdcompat).

There is something a bit delicate with copy-pasting large amount of .mli interfaces, as you have done:
- in the function documentation, `@since 4.08` should become `@since NEXT_RELEASE and OCaml 4.08`
- there is the question of copyright; when the .mli interfaces are long and detailed (more than just a couple mostly-evident lines), you should mark clearly who the original author is. (In the commit message, ; ideally you can also do a git commit with the identity of the author, instead of yourself). Could you find the authors of the _seq functions, the unsigned_ functions, and the {get,set}_int* functions, and attribute them properly?

**Comment by UnixJunkie** [comment]
> Thanks! That's a lot of work, for compatibility both with newer and older releases.
> 
> The fixes you pushed enable new library functions only on newer OCaml releases, not on older releases. Usually what we dd instead was to try to support each function (when possible: they don't rely on a runtime capatibility) on older OCaml releases as well -- so that the Batteries interface is mostly the same for all OCaml versions. This work is now carried over by [stdcompat](https://github.com/thierry-martinez/stdcompat).

Yes, I am aware of what I did. I felt it is not perfect, but better than nothing (given that I surely don't have the manpower to implement all those just by myself).

@thierry-martinez
The only problem with stdcompat is that Thierry does not guarantee that there are only
tail-recursive functions in stdcompat, IIRC.
If it was not the case, I think we should depend on stdcompat and drop all code on our side which does what stdcompat does.
Or manage to compile two versions of stdcompat: one with non tail-rec code allowed, one where it is not (and of course, batteries would depend on the second one).

> There is something a bit delicate with copy-pasting large amount of .mli interfaces, as you have done:
> 
>     * in the function documentation, `@since 4.08` should become `@since NEXT_RELEASE and OCaml 4.08`

I will fix this for sure.

>     * there is the question of copyright; when the .mli interfaces are long and detailed (more than just a couple mostly-evident lines), you should mark clearly who the original author is. (In the commit message, ; ideally you can also do a git commit with the identity of the author, instead of yourself). Could you find the authors of the _seq functions, the unsigned_ functions, and the {get,set}_int* functions, and attribute them properly?

Can't we just modify the header of the incriminated mli files and add a line to mention
that part of those mli files were provided by Inria / come from the stdlib of Inria?
That would be way simpler.

**Comment by UnixJunkie** [comment]
I still get this error on 4.07.1:
```
File "src/batteries_compattest.ml", line 105, characters 21-29:
Error: Signature mismatch:
       ...
       In module Array0:
       Modules do not match:
         (module BatBigarray.Array0)
       is not included in
         (module Bigarray.Array0)
```
I don't see any difference in the module signatures. Strange.

**Comment by UnixJunkie** [comment]
I will be in holidays soon, I will not move further until I come back.

**Comment by XVilka** [comment]
Would be nice to migrate from num to Zarith too: https://github.com/ocaml-batteries-team/batteries-included/issues/905

**Comment by gasche** [comment]
@UnixJunkie: would you like me to finish the release work, or would you prefer to do it yourself?

**Comment by UnixJunkie** [comment]
> Would be nice to migrate from num to Zarith too: #905

Please open an issue.

PS: things that are tracked eventually get done.

**Comment by UnixJunkie** [comment]
maybe I can finish today

**Comment by UnixJunkie** [comment]
I am testing if we are ready to tag:
https://github.com/ocaml/opam-repository/pull/14695

**Comment by UnixJunkie** [comment]
I am done with the release.
The ocamldoc was uploaded too.
I will announce on discuss.
Thanks to those who helped.
