### ISSUE TITLE
BatFile.nb_lines

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-batteries-team/batteries-included#951]
Quite often, when system programming while riding my caml,
I need to count the number of lines in a file.
I am tired of writing variations of this time and again, so I will send an implementation here.

**Comment by UnixJunkie** [comment]
Maybe count_lines would be a better name.

**Comment by UnixJunkie** [comment]
If someone could check that this does the right thing on windows,
that would be helpful:
```
let count_lines (fn: string): int =
  let count = ref 0 in
  let input = open_in fn in
  (try
     while true do
       let _line = input_line input in
       incr count
     done
   with End_of_file -> close_in input);
  !count
```

**Comment by rixed** [comment]
Indeed, `nb_lines` does not sound right to me. Actually `nb` may be not be very common outside France (see for instance https://www.proz.com/kudoz/french-to-english/general-conversation-greetings-letters/780428-nb-%3D-number.html for an illustration of how it can puzzle even translators).
I think `count` or `num` would be preferable.

Now, why not use one of the 3 (!) `lines_of` function that we already have? So that `count_lines` would be along the lines of `Enum.hard_count % File.lines_of` ?

**Comment by UnixJunkie** [comment]
In my experience, BatIO is inefficient compare to its stdlib counterparts.

**Comment by UnixJunkie** [comment]
was merged
